// Auto-generated by moshi-hooks — do not edit.
// Ported from opencode-moshi-live (https://github.com/young5lee/opencode-moshi-live) — MIT.
// Runs in-process inside OpenCode and POSTs lifecycle events directly to the
// Moshi API. Token is loaded from ~/.config/moshi/token.

import { homedir } from "node:os"
import { basename } from "node:path"

const TOKEN_PATH = `${homedir()}/.config/moshi/token`
const API_URL = "https://api.getmoshi.app/api/v1/agent-events"

const INTERESTING_TOOLS = new Set([
  "bash",
  "edit",
  "write",
  "read",
  "glob",
  "grep",
  "task",
  "question",
  "apply_patch",
  "webfetch",
  "websearch",
])

const COMPLETION_TTL_MS = 2_000
const PERMISSION_TTL_MS = 30_000
const QUESTION_TTL_MS = 30_000
const THINKING_TTL_MS = 10_000
const REASONING_TTL_MS = 12_000
const SUBTASK_TTL_MS = 20_000

type MoshiEvent = {
  source: "opencode"
  eventType: "pre_tool" | "post_tool" | "notification" | "stop"
  sessionId: string
  category:
    | "approval_required"
    | "task_complete"
    | "tool_running"
    | "tool_finished"
    | "info"
    | "error"
    | "thinking"
  title: string
  message: string
  eventId: string
  projectName?: string
  toolName?: string
}

type WaitReason = "permission" | "question" | "assistant_question"

type SessionState = {
  isChild?: boolean
  recentKeys?: Record<string, number>
  lastCompletionAt?: number
  lastToolName?: string
  lastToolMessage?: string
  lastToolFinishedAt?: number
  lastStepFinishSummary?: string
  lastStepFinishAt?: number
  lastRetryAt?: number
  lastRetryMessage?: string
  lastPermissionReplyAt?: number
  lastPermissionReply?: string
  lastTextReply?: string
  lastTextReplyAt?: number
  awaitingUserInput?: boolean
  awaitingPermission?: boolean
  waitReason?: WaitReason
  hadToolActivity?: boolean
  hadReasoningActivity?: boolean
}

function truncate(value: unknown, max = 240): string {
  if (typeof value !== "string") return ""
  const text = value.trim().replace(/\s+/g, " ")
  if (text.length <= max) return text
  return `${text.slice(0, max - 1)}...`
}

function stableStringify(value: unknown): string {
  return JSON.stringify(value, (_key, current) => {
    if (current && typeof current === "object" && !Array.isArray(current)) {
      return Object.keys(current)
        .sort()
        .reduce<Record<string, unknown>>((result, key) => {
          result[key] = (current as Record<string, unknown>)[key]
          return result
        }, {})
    }
    return current
  })
}

function formatToolName(tool: string): string {
  return tool.charAt(0).toUpperCase() + tool.slice(1)
}

function formatToolMessage(tool: string, args: any): string {
  switch (tool) {
    case "bash":
      return truncate(args?.description || args?.command)
    case "edit":
    case "write":
    case "read":
      return truncate(args?.filePath)
    case "glob":
      return truncate(args?.pattern)
    case "grep":
      return truncate(args?.pattern)
    case "task":
      return truncate(args?.description || args?.prompt, 160)
    case "question": {
      const questions = Array.isArray(args?.questions) ? args.questions : []
      const summaries = questions.map((question: any) => {
        const header = truncate(question?.header || "Question", 40)
        const body = truncate(question?.question || "", 120)
        return body ? `${header}: ${body}` : header
      })
      return truncate(summaries.join(" | "), 240)
    }
    case "apply_patch":
      return truncate(args?.description || args?.patchText, 180)
    case "webfetch":
      return truncate(args?.url)
    case "websearch":
      return truncate(args?.query || args?.url)
    default:
      return ""
  }
}

function formatPermissionMessage(properties: any): string {
  const permission = truncate(properties?.permission || "permission", 40)
  const patterns = Array.isArray(properties?.patterns)
    ? properties.patterns.map((pattern: unknown) => truncate(String(pattern), 80)).filter(Boolean)
    : []

  const metadata = properties?.metadata || {}
  const metadataCommand = truncate(
    typeof metadata.command === "string"
      ? metadata.command
      : typeof metadata.message === "string"
        ? metadata.message
        : typeof metadata.path === "string"
          ? metadata.path
          : "",
    160,
  )
  const details = patterns.length ? patterns.join(", ") : metadataCommand || truncate(stableStringify(metadata), 180)

  switch (permission) {
    case "read":
      return truncate(`Read access requested${details ? `: ${details}` : ""}`, 240)
    case "edit":
      return truncate(`Edit access requested${details ? `: ${details}` : ""}`, 240)
    case "bash":
      return truncate(`Command approval requested${details ? `: ${details}` : ""}`, 240)
    case "external_directory":
      return truncate(`External directory access requested${details ? `: ${details}` : ""}`, 240)
    default:
      return truncate(`${permission}${details ? `: ${details}` : ""}`, 240)
  }
}

function normalizePermissionEvent(event: any): {
  sessionID: string
  permissionType: string
  patterns: string[]
  metadata: Record<string, unknown>
} | null {
  const properties = event?.properties
  if (!properties?.sessionID) return null

  const permissionType =
    typeof properties.permission === "string"
      ? properties.permission
      : typeof properties.type === "string"
        ? properties.type
        : "permission"

  const rawPatterns = properties.patterns ?? properties.pattern
  const patterns = Array.isArray(rawPatterns)
    ? rawPatterns.map((pattern: unknown) => String(pattern))
    : rawPatterns
      ? [String(rawPatterns)]
      : []

  return {
    sessionID: String(properties.sessionID),
    permissionType,
    patterns,
    metadata: properties.metadata && typeof properties.metadata === "object" ? properties.metadata : {},
  }
}

function inferAssistantQuestion(text: string): boolean {
  const normalized = text.trim().replace(/\s+/g, " ")
  if (!normalized) return false

  if (/^(may|can|should) i\b/i.test(normalized)) return true
  if (/^(would|do) you (like|want) me to\b/i.test(normalized)) return true
  if (/^(which|what|where|when|who|how)\b/i.test(normalized) && normalized.endsWith("?")) return true
  if (/please confirm/i.test(normalized)) return true
  return normalized.endsWith("?") && normalized.length <= 220
}

async function loadToken(): Promise<string | null> {
  try {
    const text = await Bun.file(TOKEN_PATH).text()
    return text.trim() || null
  } catch {
    return null
  }
}

export default async ({ client, directory }: { client: any; directory: string }) => {
  const projectName = basename(directory)
  const sessionStates = new Map<string, SessionState>()

  async function log(level: "warn" | "error", message: string, extra?: Record<string, unknown>) {
    try {
      await client?.app?.log?.({
        body: { service: "moshi-hooks", level, message, extra },
      })
    } catch {
      // Ignore logging failures to avoid affecting agent execution.
    }
  }

  function stateFor(sessionID: string): SessionState {
    const state = sessionStates.get(sessionID)
    if (state) return state
    const created: SessionState = { recentKeys: {} }
    sessionStates.set(sessionID, created)
    return created
  }

  function remember(sessionID: string, update: Partial<SessionState>) {
    const current = stateFor(sessionID)
    sessionStates.set(sessionID, { ...current, ...update, recentKeys: current.recentKeys || {} })
  }

  function seenRecently(sessionID: string, key: string, ttlMs: number): boolean {
    const state = stateFor(sessionID)
    const recentKeys = state.recentKeys || {}
    const last = recentKeys[key]
    const now = Date.now()
    recentKeys[key] = now
    state.recentKeys = recentKeys
    sessionStates.set(sessionID, state)
    return Boolean(last && now - last < ttlMs)
  }

  async function getSessionState(sessionID: string): Promise<SessionState> {
    const state = stateFor(sessionID)
    if (state.isChild !== undefined) return state

    try {
      const response = await client?.session?.get?.({ path: { id: sessionID } })
      state.isChild = Boolean(response?.data?.parentID)
    } catch {
      state.isChild = false
    }

    sessionStates.set(sessionID, state)
    return state
  }

  async function shouldSkipSession(sessionID: string): Promise<boolean> {
    const state = await getSessionState(sessionID)
    return Boolean(state.isChild)
  }

  async function send(event: Omit<MoshiEvent, "source" | "eventId" | "projectName">): Promise<void> {
    const token = await loadToken()
    if (!token) return
    if (await shouldSkipSession(event.sessionId)) return

    try {
      const response = await fetch(API_URL, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          ...event,
          source: "opencode",
          eventId: crypto.randomUUID(),
          projectName,
        } satisfies MoshiEvent),
        signal: AbortSignal.timeout(5000),
      })

      if (!response.ok) {
        await log(response.status >= 500 ? "error" : "warn", "Moshi API rejected event", {
          status: response.status,
          title: event.title,
          category: event.category,
          eventType: event.eventType,
        })
      }
    } catch (error) {
      await log("error", "Failed to send Moshi event", {
        error: error instanceof Error ? error.message : String(error),
        title: event.title,
        category: event.category,
        eventType: event.eventType,
      })
    }
  }

  function markWaiting(sessionID: string, reason: WaitReason) {
    remember(sessionID, {
      awaitingUserInput: true,
      awaitingPermission: reason === "permission",
      waitReason: reason,
    })
  }

  function clearWaiting(sessionID: string) {
    remember(sessionID, {
      awaitingUserInput: false,
      awaitingPermission: false,
      waitReason: undefined,
    })
  }

  function buildCompletionMessage(state: SessionState): string {
    if (state.lastStepFinishSummary) {
      return truncate(`Latest step: ${state.lastStepFinishSummary}`, 220)
    }
    if (state.lastToolName) {
      const detail = state.lastToolMessage ? `: ${state.lastToolMessage}` : ""
      return truncate(`Finished after ${formatToolName(state.lastToolName)}${detail}`, 220)
    }
    if (state.lastTextReply) {
      return truncate(`Reply ready: ${state.lastTextReply}`, 220)
    }
    return "Reply ready"
  }

  setTimeout(() => {
    client?.tui?.showToast?.({
      body: { message: "moshi-hooks plugin active", variant: "info" },
    }).catch(() => {})
  }, 1200)

  return {
    event: async ({ event }: { event: any }) => {
      const rawEvent = event

      if (rawEvent.type === "permission.asked" || rawEvent.type === "permission.updated") {
        const normalized = normalizePermissionEvent(rawEvent)
        if (!normalized) return

        const permissionKey = stableStringify({
          permission: normalized.permissionType,
          patterns: normalized.patterns,
          metadata: normalized.metadata,
        })

        markWaiting(normalized.sessionID, "permission")
        if (seenRecently(normalized.sessionID, `permission:${permissionKey}`, PERMISSION_TTL_MS)) return

        await send({
          sessionId: normalized.sessionID,
          eventType: "notification",
          category: "approval_required",
          title: "Permission Required",
          message: formatPermissionMessage({
            permission: normalized.permissionType,
            patterns: normalized.patterns,
            metadata: normalized.metadata,
          }),
        })
        return
      }

      if (rawEvent.type === "permission.replied") {
        const sessionID =
          typeof rawEvent.properties?.sessionID === "string" ? rawEvent.properties.sessionID : undefined
        if (!sessionID) return
        clearWaiting(sessionID)
        remember(sessionID, {
          lastPermissionReplyAt: Date.now(),
          lastPermissionReply: truncate(
            rawEvent.properties?.reply || rawEvent.properties?.response || rawEvent.properties?.status || "replied",
            80,
          ),
        })
        return
      }

      switch (rawEvent.type) {
        case "session.idle": {
          const sessionID = rawEvent.properties.sessionID
          const state = await getSessionState(sessionID)
          const now = Date.now()

          if (state.awaitingPermission || state.waitReason === "permission") return
          if (state.awaitingUserInput && state.waitReason) return
          if (state.lastRetryAt && now - state.lastRetryAt < 15_000) return
          if (state.lastPermissionReplyAt && now - state.lastPermissionReplyAt < 3_000) return
          if (!(state.hadToolActivity || state.hadReasoningActivity || state.lastTextReply)) return
          if (state.lastCompletionAt && now - state.lastCompletionAt < COMPLETION_TTL_MS) return

          remember(sessionID, { lastCompletionAt: now })
          await send({
            sessionId: sessionID,
            eventType: "stop",
            category: "task_complete",
            title: "Task Complete",
            message: buildCompletionMessage(state),
          })

          remember(sessionID, {
            hadToolActivity: false,
            hadReasoningActivity: false,
            lastStepFinishSummary: undefined,
            lastTextReply: undefined,
          })
          return
        }

        case "session.error": {
          const sessionID = rawEvent.properties.sessionID
          if (!sessionID) return
          await send({
            sessionId: sessionID,
            eventType: "notification",
            category: "error",
            title: "Session Error",
            message: truncate(rawEvent.properties.error),
          })
          return
        }

        case "session.status": {
          const sessionID = rawEvent.properties.sessionID
          const status = rawEvent.properties.status
          if (status?.type === "retry") {
            remember(sessionID, {
              lastRetryAt: Date.now(),
              lastRetryMessage: truncate(status.message || "The agent is retrying"),
            })
            await send({
              sessionId: sessionID,
              eventType: "notification",
              category: "error",
              title: "Retrying",
              message: truncate(status.message || "The agent is retrying"),
            })
          }
          return
        }

        case "message.part.updated": {
          const part = rawEvent.properties.part
          const sessionID = part.sessionID

          if (part.type === "step-start") {
            const key = truncate(part.snapshot || "thinking", 120)
            if (seenRecently(sessionID, `step-start:${key}`, THINKING_TTL_MS)) return
            remember(sessionID, { hadReasoningActivity: true })
            await send({
              sessionId: sessionID,
              eventType: "notification",
              category: "info",
              title: "Thinking",
              message: truncate(part.snapshot || "The agent started a new reasoning step"),
            })
            return
          }

          if (part.type === "reasoning") {
            const summary = truncate(part.text, 220)
            if (!summary || summary.length < 25) return
            if (seenRecently(sessionID, `reasoning:${summary}`, REASONING_TTL_MS)) return

            remember(sessionID, { hadReasoningActivity: true })
            await send({
              sessionId: sessionID,
              eventType: "notification",
              category: "info",
              title: "Reasoning",
              message: summary,
            })
            return
          }

          if (part.type === "step-finish") {
            const reason = truncate(part.reason || part.snapshot || "Step finished", 220)
            remember(sessionID, {
              lastStepFinishSummary: reason,
              lastStepFinishAt: Date.now(),
              hadReasoningActivity: true,
            })
            await send({
              sessionId: sessionID,
              eventType: "notification",
              category: "info",
              title: "Step Complete",
              message: reason,
            })
            return
          }

          if (part.type === "subtask") {
            const summary = truncate(part.description || part.prompt, 220)
            if (seenRecently(sessionID, `subtask:${summary}`, SUBTASK_TTL_MS)) return
            await send({
              sessionId: sessionID,
              eventType: "notification",
              category: "info",
              title: "Delegating",
              message: summary,
            })
            return
          }

          if (part.type === "text") {
            const text = truncate(part.text, 240)
            if (!text) return
            remember(sessionID, { lastTextReply: text, lastTextReplyAt: Date.now() })

            if (inferAssistantQuestion(text)) {
              markWaiting(sessionID, "assistant_question")
              if (seenRecently(sessionID, `assistant-question:${text}`, QUESTION_TTL_MS)) return
              await send({
                sessionId: sessionID,
                eventType: "notification",
                category: "approval_required",
                title: "Waiting for Reply",
                message: text,
              })
            } else {
              clearWaiting(sessionID)
            }
          }
          return
        }

        default:
          return
      }
    },

    "tool.execute.before": async (input: any, output: any) => {
      const tool = String(input.tool || "").toLowerCase()
      if (!INTERESTING_TOOLS.has(tool)) return

      if (tool === "question") {
        const message = formatToolMessage(tool, output.args)
        markWaiting(input.sessionID, "question")
        if (seenRecently(input.sessionID, `question:${message}`, QUESTION_TTL_MS)) return
        await send({
          sessionId: input.sessionID,
          eventType: "notification",
          category: "approval_required",
          title: "Question",
          message,
          toolName: tool,
        })
        return
      }

      clearWaiting(input.sessionID)
      const message = formatToolMessage(tool, output.args)
      remember(input.sessionID, {
        lastToolName: tool,
        lastToolMessage: message,
        hadToolActivity: true,
      })

      await send({
        sessionId: input.sessionID,
        eventType: "pre_tool",
        category: "tool_running",
        title: `Running ${formatToolName(tool)}`,
        message,
        toolName: tool,
      })
    },

    "tool.execute.after": async (input: any, output: any) => {
      const tool = String(input.tool || "").toLowerCase()
      if (!INTERESTING_TOOLS.has(tool) || tool === "question") return

      const message = truncate(output.title || output.output, 220)
      remember(input.sessionID, {
        lastToolName: tool,
        lastToolMessage: message || stateFor(input.sessionID).lastToolMessage,
        lastToolFinishedAt: Date.now(),
        hadToolActivity: true,
      })

      await send({
        sessionId: input.sessionID,
        eventType: "post_tool",
        category: "tool_finished",
        title: `Finished ${formatToolName(tool)}`,
        message,
        toolName: tool,
      })
    },
  }
}
